################################################
# Visulaization v2 makefile.
# (c) Jon DuBois 2004
# 10/22/2004
# See license.txt for license details.
################################################
LDFLAGS = -lstdc++ -lmingw32 -lSDLmain -lSDL -mwindows -luser32 -lgdi32 -lwinmm -lopengl32
TEST = test.exe
LIB = libvis.a
LIBOBJS = engine.o draw.o context.o surface.o assess.o
TESTOBJS = test.o engine.o draw.o context.o surface.o assess.o
HDRS = engine.H draw.H context.H surface.H geometry.H vis.H geometry.cpp lighting.H

PROJECT = vislibsdl
PROJECTINC = vis

include Mother.Makefile



