################################################
# Visulaization v2 makefile.
# (c) Jon DuBois 2004
# 10/22/2004
# This file is licensed via the GPL.
# See license.txt for license details.
# THIS SOFTWARE HAS NO WARRANTY.
################################################
LDFLAGS = -lopengl32 -lgdi32 -lstdc++ -lcg -lcgGL
TEST = test.exe
BIN = gears.exe
LIB = libvis.a
LIBNAME = vis
LIBOBJS = engine.o draw.o display.o surface.o assess.o cgshader.o
TESTOBJS = test.o
BINOBJS = gears.o resource.o
HDRS = engine.H draw.H display.H surface.H geometry.H vis.H lighting.H resource.H wglext.H algo.H stack.H cgshader.H

PROJECT = vislib
PROJECTINC = vis

include Mother.Makefile



