################################################
# Bcjlib makefile.
# (c) Jon DuBois 2004
# 02/25/2004
# See license.txt for license details.
################################################
LDFLAGS = -lstdc++
TEST = test
LIB = libbcj.a
LIBOBJS = assess.o string.o cgiparse.o gregex.o cregex.o
TESTOBJS = test.o assess.o string.o cgiparse.o gregex.o cregex.o
HDRS = algo.H assess.H cgiparse.H cregex cowa.H gregex.H stack.H string.H bcjlib.H list.H

PROJECT = bcjlib
PROJECTINC = bcj

include Mother.Makefile